AWSTemplateFormatVersion: '2010-09-09'
Resources:
  :
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 
      Handler: saludo_simple.saludo_simple.handler
      Runtime: python3.9
      CodeUri: 
      Timeout: 30
      MemorySize: 128
