name: Deploy single Lambda 

on:
  push:
    branches:
      -main

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: checkout source code
      uses: actions/checkout@v3
    - name: deploy suma lambda
      uses: appleboy/lambda-action@v0.2.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: saludo_simple
        source: app.saludo_simple.saludo_simple.py