name: Deploy Python Lambda Function

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      
      - name: Zip the function code
        run: |
          mkdir -p package
          cp app/saludo_simple/saludo_simple.py package/
          cd package
          zip -r function.zip saludo_simple.py
          cd ..

      
      - name: Deploy to Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
        run: |
          aws lambda update-function-code \
            --function-name saludo_simple \
            --zip-file fileb://package/function.zip

      
      - name: Cleanup
        run: rm -rf package/
